In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/sales-data-for-economic-data-analysis/salesforcourse-4fe2kehu.csv
/kaggle/input/sales-data-for-economic-data-analysis/salesforcourse-4fe2kehu.xlsx

In [3]:
df = pd.read_csv("/kaggle/input/sales-data-for-economic-data-analysis/salesforcourse-4fe2kehu.csv")
df

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Column1
0,0,2/19/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.000000,NaN
1,1,2/20/2016,2016.0,February,29.0,F,United States,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.000000,NaN
2,2,2/27/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.000000,NaN
3,3,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.000000,NaN
4,4,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34862,34862,2/7/2016,2016.0,February,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,2.0,1160.00,985.500000,2320.0,1971.000000,NaN
34863,34863,3/13/2015,2015.0,March,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2049.00,1583.000000,2049.0,1583.000000,NaN
34864,34864,4/5/2015,2015.0,April,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,3.0,683.00,560.666667,2049.0,1682.000000,NaN
34865,34865,8/30/2015,2015.0,August,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2320.00,1568.000000,2320.0,1568.000000,NaN
34866,34866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,641.532095,NaN

Analysis Questions :
    
What is the overall revenue for the entire dataset?

How does the revenue vary over the years?

What is the average quantity sold per month?

Can you identify the top-selling product categories?

What is the distribution of customer ages in the dataset?

How does the average unit cost and unit price vary by product category?

What is the total cost and revenue for each product category?

Are there any outliers in the quantity sold or unit price?

What is the most common product sub-category sold?

How does the revenue vary by customer gender?

Can you identify the highest revenue-generating states?

What is the average quantity sold per product sub-category?

How has the sales quantity changed over the years?

What is the average unit cost and unit price per state?

Can you identify any seasonality in the sales data?

What is the total revenue for each country?

Are there any correlations between customer age and revenue?

How does the quantity sold vary by product category and sub-category?

What is the distribution of customer ages by gender?

Can you identify any trends in the sales data using a moving average?

What is the percentage contribution of each product category to the total revenue?

How do unit cost and unit price vary by country?

What is the total revenue for each year and month?

Can you identify any patterns in customer purchasing behavior?

What is the average revenue per customer by state?

Are there any significant differences in revenue between countries?

How does the unit price impact the quantity sold?

Can you identify any outliers in the customer age distribution?

What is the average revenue per product category?

How does the revenue vary by month and product category?

What is the average unit cost and unit price per year?

Are there any trends in the sales data based on customer gender?

What is the total revenue for each product sub-category?

How does the sales quantity correlate with unit price?

Can you identify any patterns in customer purchasing over the months?

What is the distribution of customer ages in each state?

How does the revenue vary by year and state?

What is the average revenue per customer by country?

Can you identify any outliers in the cost and revenue columns?

How has the quantity sold changed over the months?

What is the total revenue for each product sub-category and year?

How does the average unit price vary by product sub-category?

Can you identify any patterns in the sales data using a rolling window?

What is the average revenue per customer by product category?

How does the sales quantity vary by state and product category?

What is the total revenue for each state and product category?

Can you identify any correlations between unit cost and unit price?

How does the quantity sold vary by year and product category?

What is the average unit cost and unit price per month?

Can you identify any patterns or anomalies in the 'Column1' column?